<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSSimulationWSServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSSimulationWSServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSSimulationWSServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://simulation/">
    <import location="SimulationWSService.wsdl" namespace="http://simulation/"/>
    <plnk:partnerLinkType name="SimulationWSLinkType">
        <plnk:role name="SimulationWSRole" portType="ns:SimulationWS"/>
    </plnk:partnerLinkType>
</definitions>

